server.port=8761
spring.application.name=service-registry
spring.cloud.config.enabled=false

eureka.instance.prefer-ip-address=true
eureka.instance.appname=SERVICE-REGISTRY

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://vm-node-a.platform:8761/eureka/,http://vm-node-b.platform:8761/eureka/,http://vm-node-c.platform:8761/eureka/

eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=60000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
