eureka.region=default
eureka.name=service-registry
eureka.vipAddress=service-registry
eureka.port=8761
eureka.preferSameZone=true
eureka.shouldUseDns=false
eureka.serviceUrl.defaultZone=http://vm-node-a.platform:8761/eureka/,http://vm-node-b.platform:8761/eureka/,http://vm-node-c.platform:8761/eureka/
